### PR TITLE
Some initial thoughts for Blender description

### PR DESCRIPTION
**Pull request by BradyAJohnston**
@yuxuanzhuang can probably comment as well

related to #12

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
This looks all very interesting to me.

I wouldn't know where to start, though, and might feel intimidated to join if I wasn't already a blender guru. Perhaps include some links to where people can educate themselves a bit more on blender/python things?

Nevertheless, there's no formal review process for your own workshop materials. I'd just merge and you or @yuxuanzhuang should be able to do this yourself now.

**Comment by BradyAJohnston** [comment]
Thanks @orbeckst I'll add in some more details and we can try and formalise some smaller goals that are more achievable

**Comment by yuxuanzhuang** [comment]
This all looks quite good!

Regarding the required background knowledge, it would be beneficial to compile a list of materials for each potential project. Additionally, I found that the [Blender Python API documentation](https://docs.blender.org/api/current/index.html) e.g. `bpy.types.Operator`, can be somewhat daunting.

It's important to note that one doesn't need to be a Blender guru to implement some of these concepts (I certainly am not). Including practical code examples, such as how to draw a line in Blender using Python, could be a valuable resource for individuals looking to quickly get some prototypes working.

**Comment by BradyAJohnston** [comment]
Yes we should put together some "getting started" in terms of explaining how operators work and how to actually do some basic tasks inside of Blender.

**Pull request merged**
